# See: https://dart.dev/tools/pub/pubspec
name: model_viewer_plus
version: 1.3.3
description: >-
  A Flutter widget for rendering interactive 3D models in the glTF and GLB
  formats.
homepage: https://github.com/omchiii/model_viewer_plus.dart
repository: https://github.com/omchiii/model_viewer_plus.dart
issue_tracker: https://github.com/omchiii/model_viewer_plus.dart/issues
platforms:
  android:
  ios:
  web:
dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^3.1.1
  webview_flutter:
    git:
      url: https://github.com/suehok/plugins.git
      ref: main
      path: packages/webview_flutter/webview_flutter
  url_launcher: ^6.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
environment:
  sdk: ">=2.12.0 <3.0.0"
flutter:
  assets:
    - assets/
